ctfd-writeups/blueprint.py
import re
from collections import defaultdict
from CTFd.utils.decorators import admins_only, during_ctf_time_only, require_verified_emails, require_team, authed_only
from CTFd.utils.user import authed, get_current_user
from CTFd.utils import markdown
from flask import request, render_template, Blueprint, abort, redirect, url_for, send_from_directory
from CTFd.models import db, Challenges, Submissions, Solves, Pages
from .models import WriteUpChallenges, Duplicate
import cmarkgfm
from cmarkgfm.cmark import Options as cmarkgfmOptions

writeups_bp = Blueprint("writeups", __name__, template_folder="templates")


def load_bp(admin_route, base_route, plugin_dir='.'):
    @writeups_bp.route(f"{base_route}/assets/<path:path>", methods=["GET"])
    def assets(path: str):
        return send_from_directory(f"{plugin_dir}/assets", path)

    @writeups_bp.route(admin_route, methods=["POST"])
    @admins_only
    def update_config():
        form = request.form.to_dict()
        del form['nonce']

        challenges = defaultdict(lambda: {})

        for k, v in form.items():
            match = re.match(r'(?P<id>\d+)-(?P<prop>[a-zA-Z0-9-_]+)', k)
            if match:
                challenges[int(match.group('id'))][match.group('prop')] = v
            else:
                print(f"Unrecognized form key {k}")

        for challenge_id, props in challenges.items():
            challenge = Challenges.query.get(challenge_id)
            if 'accepting_wu' in props:
                if not challenge.writeup_challenge:
                    challenge.writeup_challenge = WriteUpChallenges(
                        name=f"Write-Up for {challenge.name}",
                        description='',
                        category='Write-Ups')
                challenge.writeup_challenge.value = props.get('wu_value', 5)
                challenge.writeup_challenge.solve_req = 'vis_before_solve' not in props
                submit_str = f"\n\n[Submit a write-up]({url_for('writeups.edit_writeup', challenge_id=challenge.id)}) for this challenge (+{challenge.writeup_challenge.value} pts.) or [view others']({url_for('writeups.writeups', challenge=challenge.id)}) write-ups."
                submit_re = r'\[Submit a write-up]\(.+\) for this challenge \(\+\d+ pts\.\) or \[view others\']\(.+\) write-ups\.'
                if not re.search(submit_re, challenge.description):
                    challenge.description += submit_str
                else:
                    challenge.description = re.sub(submit_re, submit_str, challenge.description)
            elif challenge.writeup_challenge:
                db.session.delete(challenge.writeup_challenge)

        db.session.commit()
        return get_config()

    @writeups_bp.route(admin_route, methods=["GET"])
    @admins_only
    def get_config():
        challenges = db.session.query(Challenges).filter(Challenges.type != 'writeup').all()
        submissions = (db.session.query(Submissions).join(WriteUpChallenges,
                                                          Submissions.challenge_id == WriteUpChallenges.id)).all()

        rows = []
        for challenge in challenges:
            rows.append({
                'id': challenge.id,
                'name': challenge.name,
                'value': challenge.value,
                'accepting_wu': bool(challenge.writeup_challenge),
                'wu_value': challenge.writeup_challenge.value if challenge.writeup_challenge else 0,
                'solve_req': challenge.writeup_challenge.solve_req if challenge.writeup_challenge else True
            })

        return render_template("writeups_admin.html", challenges=rows, writeups=submissions)

    @writeups_bp.route(base_route, methods=["GET"])
    @during_ctf_time_only
    @authed_only
    def writeups():
        user = get_current_user()
        page = db.session.query(Pages).filter(Pages.route == base_route).one_or_none()

        if user.type == 'admin':
            visible_writeups = (db.session.query(Submissions)
                                .join(WriteUpChallenges, Submissions.challenge_id == WriteUpChallenges.id))
        else:
            solves_ids = [s.challenge_id for s in user.team.solves] if user.team else []
            visible_writeups = (db.session.query(Submissions)
                                .join(WriteUpChallenges, Submissions.challenge_id == WriteUpChallenges.id)
                                .filter(WriteUpChallenges.for_id.in_(solves_ids) |
                                        ~WriteUpChallenges.solve_req |
                                        (Submissions.user_id == user.id)))

        if 'challenge' in request.args:
            visible_writeups = visible_writeups.filter(WriteUpChallenges.for_id == request.args['challenge'])

        visible_writeups = visible_writeups.all()
        return render_template("writeups.html", writeups=visible_writeups, page_content=page.content if page else '')

    @writeups_bp.route(f"{base_route}/<int:writeup_id>", methods=["GET"])
    @during_ctf_time_only
    @authed_only
    def view_writeup(writeup_id: int):
        user = get_current_user()
        writeup = db.session.query(Submissions).get(writeup_id)
        error = {}
        content = ''
        editable = False

        if writeup.challenge.type != 'writeup':
            return redirect(url_for('writeups.writeups'))

        challenge = (db.session.query(Challenges)
                     .filter(Challenges.type != 'writeup')
                     .filter(Challenges.writeup_challenge == writeup.challenge)
                     .one_or_none())

        if not challenge or not challenge.writeup_challenge:
            return redirect(url_for('writeups.writeups'))

        if (user.type == 'admin' or
                not challenge.writeup_challenge.solve_req or
                challenge.id in (s.challenge_id for s in user.team.solves) or
                writeup.user.id == user.id):
            content = cmarkgfm.github_flavored_markdown_to_html(writeup.provided, options=cmarkgfmOptions.CMARK_OPT_SAFE)
            if writeup.user.id == user.id or user.type == 'admin':
                editable = True
        else:
            error = {
                'heading': '403',
                'msg': 'Sorry, you must solve this challenge before viewing write-ups for it'
            }
        return render_template("view_writeup.html",
                               challenge=challenge,
                               content=content,
                               error=error,
                               user=writeup.user,
                               editable=editable)

    @writeups_bp.route(f"{base_route}/<int:challenge_id>/edit", methods=["GET", "POST"])
    @during_ctf_time_only
    @authed_only
    def edit_writeup(challenge_id: int):
        user = get_current_user()
        challenge = (db.session.query(Challenges)
                       .filter(Challenges.id == challenge_id)
                       .filter(Challenges.type != 'writeup')
                       .one_or_none())

        if not challenge or not challenge.writeup_challenge:
            return redirect(url_for('writeups.writeups'))

        solves = [s.challenge_id for s in user.team.solves] if user.team else [s.challenge_id for s in user.solves]

        if challenge.id not in solves:
            return render_template("edit_writeup.html", challenge=challenge, error={
                'heading': '403',
                'msg': 'Sorry, you must solve the challenge before submitting a write-up'
            })

        writeup = (db.session.query(Submissions)
                     .filter(Submissions.challenge_id == challenge.writeup_challenge.id)
                     .filter(Submissions.user_id == user.id)
                     .one_or_none())

        if not writeup:
            team_wu_solve = (db.session.query(Solves)
                               .filter(Solves.challenge_id == challenge.writeup_challenge.id)
                               .filter(Solves.team_id == user.team.id)
                               .one_or_none())
            if team_wu_solve:
                writeup = Duplicate(
                    challenge=challenge.writeup_challenge,
                    user=user,
                    team=user.team,
                    ip=request.remote_addr,
                    provided='',
                )
            else:
                writeup = Solves(
                    challenge=challenge.writeup_challenge,
                    user=user,
                    team=user.team,
                    ip=request.remote_addr,
                    provided='',
                )
            db.session.add(writeup)
            db.session.flush()

        if request.method == 'POST':
            writeup.provided = request.form.to_dict().get('content', '')
            res = redirect(url_for('writeups.view_writeup', writeup_id=writeup.id))
            db.session.commit()
            return res
        elif request.method == 'GET':
            return render_template("edit_writeup.html", challenge=challenge, writeup=writeup)

    # Add the Write-Ups page to pages so it appears in the nav bar
    if not db.session.query(Pages).filter(Pages.route == base_route).one_or_none():
        with open(f"{plugin_dir}/assets/writeups_default.html", 'r') as fd:
            db.session.add(Pages(
                title='Write-Ups',
                route=base_route,
                content=fd.read(),
                draft=False,
                hidden=False,
                auth_required=True
            ))
            db.session.commit()

    return writeups_bp

ctfd-writeups/templates/edit_writeup.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<div class="jumbotron">
	<div class="container">
		<h1>Write-Up for {{ challenge.name }}</h1>
	</div>
</div>
<div class="container">
	{% if error %}
	<div class="row">
		<div class="col-md-12">
			<div class="pt-5 mt-5 text-center">
				<h1>{{ error.heading }}</h1>
				<hr class="w-50">
				<h2>{{ error.msg }}</h2>
			</div>
		</div>
	</div>
	{% else %}
	<div class="row">
		<div class="col-md-12">
			<form method="POST">

				<div class="form-group">
					<div class="col-md-12">
						<h3>{{ challenge.name }}</h3>
						<hr>
						<p>Type your write-up here. The first line will be used as the title.</p>
						<p>We encourage you to submit a write-ups detailing your process and what you tried (even if you
						   didn't solve the challenge) and browse through others' write-ups. They don't have to be
						   extensive masterpieces, just enough that someone with some limited familiarity with the
						   relevant concepts can follow along. Write-ups that are blatantly lazy point grabs (i.e.
						   a single sentence) won't be awarded points.</p>
						<small class="text-muted"><a href="https://www.markdownguide.org/basic-syntax/">Markdown</a> is supported</small>
						<textarea class="d-none" id="writeup-content-editor" name="content" style="display:none;">{{ writeup.provided }}</textarea>
					</div>
				</div>

				<div class="form-group float-right">
					<input type="hidden" value="{{ Session.nonce }}" name="nonce" id="nonce" />
					<a class="btn btn-primary" href="{{ url_for('writeups.view_writeup', writeup_id=writeup.id) }}">Cancel</a>
					<button class="btn btn-primary" type="submit">Save</button>
				</div>

			</form>
		</div>
	{% endif %}

</div>
{% endblock %}

{% block scripts %}
	<script defer src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('writeups.assets', path='editor.js') }}"></script>
{% endblock %}

ctfd-writeups/templates/view_writeup.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Write-Up for {{ challenge.name }}</h1>
		<small class="text-muted">By {{ user.name }} of {{ user.team.name }}</small>
	</div>
</div>
<div class="container">
	{% if error %}
	<div class="row">
		<div class="col-md-12">
			<div class="pt-5 mt-5 text-center">
				<h2>{{ error.msg }}</h2>
			</div>
		</div>
	</div>
	{% else %}
	<div class="row">
		<div class="col-md-12">
			<a href="{{ url_for('writeups.writeups') }}" class="btn btn-md btn-primary btn-outlined float-left">Back to Write-Ups</a>
			{% if editable %}
			<a href="{{ url_for('writeups.edit_writeup', challenge_id=challenge.id) }}" class="btn btn-md btn-primary btn-outlined float-right">Edit</a>
			{% endif %}
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
			{{ content | safe }}
		</div>
	</div>
	{% endif %}

</div>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/pages/main.js') }}"></script>
{% endblock %}

ctfd-writeups/templates/writeups.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Write-Ups</h1>
	</div>
</div>
<div class="container">
	{{ page_content | safe }}
	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped">
				<thead>
					<tr>
						<td scope="col" width="200px"><b>Challenge</b></td>
						<td scope="col"><b>User</b></td>
						<td scope="col"><b>Team</b></td>
						<td scope="col"><b>Title</b></td>
					</tr>
				</thead>
				<tbody>
				{% for writeup in writeups %}
					<tr>
						<th scope="row"><a href="{{ url_for('challenges.listing') }}#{{ writeup.challenge.wu_for.name }}-{{ writeup.challenge.for_id }}">{{ writeup.challenge.wu_for.name }}</a></th>
						<td>{{ writeup.user.name }}</td>
						<td>{{ writeup.user.team.name }}</td>
						<td><a href="{{ url_for('writeups.view_writeup', writeup_id=writeup.id) }}">{{ writeup.provided.split('\n')[0].strip('#') | trim }}</a></td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block entrypoint %}
{% endblock %}

ctfd-writeups/templates/writeups_admin.html
{% extends "admin/base.html" %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ url_for('views.themes', theme='admin', path='css/challenge-board.css') }}">
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Write-Ups
				<!--<a class="no-decoration" href="{{ url_for('admin.challenges_new') }}">
					<span role="button" data-toggle="tooltip" title="Create Challenge">
						<i class="btn-fa fas fa-plus-circle"></i>
					</span>
				</a>-->
			</h1>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<nav class="nav nav-tabs nav-fill" id="challenge-properties" role="tablist">
					<a class="nav-item nav-link active" data-toggle="tab" href="#challenges" role="tab" >Challenges</a>
					<a class="nav-item nav-link" data-toggle="tab" href="#submissions" role="tab">Submissions</a>
				</nav>

				<div class="tab-content" id="nav-tabContent">
					<div class="tab-pane fade show active" id="challenges" role="tabpanel">
						<div class="row">
							<div class="col-md-12">
								<h3 class="text-center py-3 d-block">Challenges</h3>
								{% if challenges %}
								<div id="challenges-list" class="row">
									<div class="col-md-12">
										<form method="POST">
											<button type="submit" class="btn btn-md btn-primary btn-outlined float-right">Save</button>
											<table class="table table-striped">
												<thead>
													<tr>
														<td></td>
														<td scope="col" width="250px"><b>Name</b></td>
														<td scope="col"><b>Challenge Points</b></td>
														<td scope="col"><b>Accepting Write-Ups</b></td>
														<td scope="col"><b>Write-Up Points</b></td>
														<td scope="col"><b>Write-Ups Visible Before Solve</b></td>
													</tr>
												</thead>
												<tbody>
												{% for challenge in challenges %}
													<tr>
														<th scope="row" class="text-center">{{ loop.index }}</th>
														<td>{{ challenge.name }}</td>
														<td>{{ challenge.value }}</td>
														<td>
															<input type="checkbox" value="1" name="{{ challenge.id }}-accepting_wu" {{ 'checked' if challenge.accepting_wu else '' }}>
														</td>
														<td>
															<input type="number" style="width:5em" name="{{ challenge.id }}-wu_value" value="{{ challenge.wu_value }}">
														</td>
														<td>
															<input type="checkbox" name="{{ challenge.id }}-vis_before_solve" value="1" {{ '' if challenge.solve_req else 'checked' }}>
														</td>
													</tr>
												{% endfor %}
												</tbody>
											</table>
											<input type="hidden" value="{{ Session.nonce }}" name="nonce" id="nonce" />
											<button type="submit" class="btn btn-md btn-primary btn-outlined float-right">Save</button>
										</form>
									</div>
								</div>
								{% endif %}
							</div>
						</div>
					</div>
					<div class="tab-pane fade" id="submissions" role="tabpanel">
						<div class="row">
							<div class="col-md-12">
								<h3 class="text-center py-3 d-block">Submissions</h3>
								<table class="table table-striped">
									<thead>
										<tr>
											<td scope="col" width="200px"><b>Challenge</b></td>
											<td scope="col"><b>User</b></td>
											<td scope="col"><b>Team</b></td>
											<td scope="col"><b>Title</b></td>
										</tr>
									</thead>
									<tbody>
									{% for writeup in writeups %}
										<tr>
											<th scope="row"><a href="{{ url_for('challenges.listing') }}#{{ writeup.challenge.wu_for.name }}-{{ writeup.challenge.for_id }}">{{ writeup.challenge.wu_for.name }}</a></th>
											<td>{{ writeup.user.name }}</td>
											<td>{{ writeup.user.team.name }}</td>
											<td><a href="{{ url_for('writeups.view_writeup', writeup_id=writeup.id) }}">{{ writeup.provided.split('\n')[0].strip('#') | trim }}</a></td>
										</tr>
									{% endfor %}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/pages/main.js') }}"></script>
{% endblock %}

{% block scripts %}
{% endblock %}